#!/bin/bash

source /opt/rh/igcc-toolset-9/enable
#source /opt/rh/rh-git218/enable
source /opt/intel/compilers_and_libraries_2020.4.304/linux/bin/compilervars.sh intel64

export PATH=/usr/lib64/openmpi3/bin:$PATH

bash -c "$*"
