version: "3.2"

services:
  licserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: licserver
    container_name: licence_server
    hostname: licserver
    mac_address: 02:42:ac:11:65:41
    ports:
      - 5053:5053
      - 5054:5054
    volumes:
      - licences:/opt/rlm/licences

volumes:
  licences:
