#!bin/bash

# Get file
#wget http://packages.zenotech.com/parallel_studio_xe_2017_update6.tgz

# Untar
#tar xvf parallel_studio_xe_2017_update6.tgz

#rm -f parallel_studio_xe_2017_update6.tgz

# Configure silent install
sed -i 's/ACCEPT_EULA=decline/ACCEPT_EULA=accept/' parallel_studio_xe_2017_update6/silent.cfg
sed -i 's/ACTIVATION_TYPE=exist_lic/ACTIVATION_TYPE=license_server/' parallel_studio_xe_2017_update6/silent.cfg
sed -i 's/#ACTIVATION_LICENSE_FILE=/ACTIVATION_LICENSE_FILE=28518@172.20.3.36/' parallel_studio_xe_2017_update6/silent.cfg

# Open tunnel
#ssh -f -N -T -M -F ~/.ssh/docker_config intellic

# Run install
pushd parallel_studio_xe_2017_update6 && ./install.sh --silent silent.cfg && popd

# Clean up
rm -rf parallel_studio_xe_2017_update6

# Close tunnel
#ssh -T -O "exit" -F ~/.ssh/docker_config intellic
