#!/bin/bash

echo "export GIT_AUTHOR_NAME=${GIT_AUTHOR_NAME}" >> /etc/profile.d/compose.sh
echo "export GIT_AUTHOR_EMAIL=${GIT_AUTHOR_EMAIL}" >> /etc/profile.d/compose.sh
echo "export GIT_COMMITTER_NAME=${GIT_COMMITTER_NAME}" >> /etc/profile.d/compose.sh
echo "export GIT_COMMITTER_EMAIL=${GIT_COMMITTER_EMAIL}" >> /etc/profile.d/compose.sh
echo "export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> /etc/profile.d/compose.sh
echo "export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> /etc/profile.d/compose.sh
echo "export DISPLAY=${DISPLAY}" >> /etc/profile.d/compose.sh

exec $*
